[package]
name = "dprint-plugin-mesonbuild"
version = "0.1.0"
authors = ["Tice Cosmos <tice@139.com>"]
edition = "2018"


[lib]
crate-type = ["lib", "cdylib"]


[dependencies]
dprint-core = { version = "0.42", features = ["formatting", "wasm"] }

serde = { version = "*", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
lazy_static = "1.4"
toml = "0.5"
